NZ seasons are flipped, so Feb = peak summer, Apr = early autumn.

In [9]:
import pandas as pd

In [10]:
df_sum_feb = pd.read_csv("../data/raw/listings_summary_feb2026.csv")
df_sum_apr = pd.read_csv("../data/raw/listings_summary_apr2026.csv")
df_feb = pd.read_csv("../data/raw/listings_feb2026.csv.gz")
df_apr = pd.read_csv("../data/raw/listings_apr2026.csv.gz")

In [11]:
df_sum_feb.shape

(48692, 18)

In [12]:
df_sum_feb.columns.tolist()

['id',
 'name',
 'host_id',
 'host_name',
 'neighbourhood_group',
 'neighbourhood',
 'latitude',
 'longitude',
 'room_type',
 'price',
 'minimum_nights',
 'number_of_reviews',
 'last_review',
 'reviews_per_month',
 'calculated_host_listings_count',
 'availability_365',
 'number_of_reviews_ltm',
 'license']

In [13]:
df_sum_feb.dtypes

id                                  int64
name                                  str
host_id                             int64
host_name                             str
neighbourhood_group                   str
neighbourhood                         str
latitude                          float64
longitude                         float64
room_type                             str
price                             float64
minimum_nights                    float64
number_of_reviews                   int64
last_review                           str
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
number_of_reviews_ltm               int64
license                           float64
dtype: object

In [14]:
df_sum_feb.head(3)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,1065244682287350993,Totara Ridge,120675713,Melanie,Rotorua District,Area Outside Ward,-38.16076,176.301700,Entire home/apt,NaN,1.0,141,2026-02-06,5.65,1,215,64,NaN
1,43834420,Two Bedroom Access Apartment @ Riverlodge Motel,342336273,Riverlodge Nelson,Nelson City,Area Outside Ward,-41.26832,173.287260,Entire home/apt,NaN,1.0,17,2025-02-26,0.26,11,264,1,NaN
2,650824893416631133,HOT TUB 4 bdr lake/town 5 min drive,129957281,Brendan,Queenstown-Lakes District,Wanaka Ward,-44.68137,169.157915,Entire home/apt,NaN,1.0,305,2026-02-01,6.94,15,64,67,NaN

In [15]:
df_sum_apr.shape

(48951, 18)

In [16]:
df_sum_apr.columns.tolist()

['id',
 'name',
 'host_id',
 'host_name',
 'neighbourhood_group',
 'neighbourhood',
 'latitude',
 'longitude',
 'room_type',
 'price',
 'minimum_nights',
 'number_of_reviews',
 'last_review',
 'reviews_per_month',
 'calculated_host_listings_count',
 'availability_365',
 'number_of_reviews_ltm',
 'license']

In [17]:
df_sum_apr.dtypes

id                                  int64
name                                  str
host_id                             int64
host_name                             str
neighbourhood_group                   str
neighbourhood                         str
latitude                          float64
longitude                         float64
room_type                             str
price                             float64
minimum_nights                    float64
number_of_reviews                   int64
last_review                           str
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
number_of_reviews_ltm               int64
license                           float64
dtype: object

In [18]:
df_sum_apr.head(3)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,36194,The Wharf Hub - a voyage,128489,Lloyd,Ōpōtiki District,Waioeka-Waiotahi Ward,-37.99937,177.28239,Private room,150.0,1.0,12,2017-02-26,0.07,1,88,0,NaN
1,46071,Kamahi,202747,Donna,Taupo District,Turangi-Tongariro Ward,-38.90862,175.75285,Entire home/apt,360.0,2.0,29,2025-04-21,0.36,2,290,0,NaN
2,51362,PORTAGE HEIGHTS MARLBOROUGH SOUNDS,236005,Ralph & Cynthia,Marlborough District,Marlborough Sounds Ward,-41.19326,174.03374,Private room,343.0,2.0,77,2026-04-05,0.52,1,177,4,NaN

In [19]:
df_feb.shape

(48692, 85)

In [28]:
df_feb.columns.tolist()

['id',
 'listing_url',
 'scrape_id',
 'last_searched',
 'last_scraped',
 'source',
 'name',
 'description',
 'neighborhood_overview',
 'picture_url',
 'host_id',
 'host_url',
 'host_name',
 'host_since',
 'host_location',
 'host_about',
 'host_response_time',
 'host_response_rate',
 'host_acceptance_rate',
 'host_is_superhost',
 'host_thumbnail_url',
 'host_picture_url',
 'host_neighbourhood',
 'host_listings_count',
 'host_total_listings_count',
 'host_verifications',
 'host_has_profile_pic',
 'host_identity_verified',
 'neighbourhood',
 'latitude',
 'longitude',
 'property_type',
 'room_type',
 'accommodates',
 'bathrooms',
 'bathrooms_text',
 'bedrooms',
 'beds',
 'amenities',
 'price',
 'minimum_nights',
 'maximum_nights',
 'minimum_minimum_nights',
 'maximum_minimum_nights',
 'minimum_maximum_nights',
 'maximum_maximum_nights',
 'minimum_nights_avg_ntm',
 'maximum_nights_avg_ntm',
 'calendar_updated',
 'has_availability',
 'availability_30',
 'availability_60',
 'availability_90',
 'availability_365',
 'calendar_last_scraped',
 'number_of_reviews',
 'number_of_reviews_ltm',
 'number_of_reviews_l30d',
 'availability_eoy',
 'number_of_reviews_ly',
 'estimated_occupancy_l365d',
 'estimated_revenue_l365d',
 'first_review',
 'last_review',
 'review_scores_rating',
 'review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'requires_license',
 'license',
 'instant_bookable',
 'calculated_host_listings_count',
 'calculated_host_listings_count_entire_homes',
 'calculated_host_listings_count_private_rooms',
 'calculated_host_listings_count_shared_rooms',
 'region_id',
 'region_name',
 'region_parent_id',
 'region_parent_name',
 'region_parent_parent_id',
 'region_parent_parent_name',
 'reviews_per_month']

In [24]:
print(df_feb.dtypes.to_string())

id                                                int64
listing_url                                         str
scrape_id                                         int64
last_searched                                       str
last_scraped                                        str
source                                              str
name                                                str
description                                         str
neighborhood_overview                           float64
picture_url                                         str
host_id                                           int64
host_url                                            str
host_name                                           str
host_since                                      float64
host_location                                       str
host_about                                          str
host_response_time                              float64
host_response_rate                              float64
host_acceptance_rate                            float64
host_is_superhost                                   str
host_thumbnail_url                              float64
host_picture_url                                    str
host_neighbourhood                              float64
host_listings_count                             float64
host_total_listings_count                       float64
host_verifications                              float64
host_has_profile_pic                                str
host_identity_verified                              str
neighbourhood                                   float64
latitude                                        float64
longitude                                       float64
property_type                                       str
room_type                                           str
accommodates                                      int64
bathrooms                                       float64
bathrooms_text                                      str
bedrooms                                        float64
beds                                            float64
amenities                                           str
price                                           float64
minimum_nights                                  float64
maximum_nights                                  float64
minimum_minimum_nights                          float64
maximum_minimum_nights                          float64
minimum_maximum_nights                          float64
maximum_maximum_nights                          float64
minimum_nights_avg_ntm                          float64
maximum_nights_avg_ntm                          float64
calendar_updated                                float64
has_availability                                    str
availability_30                                   int64
availability_60                                   int64
availability_90                                   int64
availability_365                                  int64
calendar_last_scraped                               str
number_of_reviews                                 int64
number_of_reviews_ltm                             int64
number_of_reviews_l30d                            int64
availability_eoy                                  int64
number_of_reviews_ly                              int64
estimated_occupancy_l365d                         int64
estimated_revenue_l365d                         float64
first_review                                        str
last_review                                         str
review_scores_rating                            float64
review_scores_accuracy                          float64
review_scores_cleanliness                       float64
review_scores_checkin                           float64
review_scores_communication                     float64
review_scores_location                          float64
review_scores_value                             float64
requires_license                                float64
license                                         float64
instant_bookable                                float64
calculated_host_listings_count                    int64
calculated_host_listings_count_entire_homes       int64
calculated_host_listings_count_private_rooms      int64
calculated_host_listings_count_shared_rooms       int64
region_id                                         int64
region_name                                         str
region_parent_id                                  int64
region_parent_name                                  str
region_parent_parent_id                         float64
region_parent_parent_name                       float64
reviews_per_month                               float64

In [15]:
df_feb.head(3)

,id,listing_url,scrape_id,last_searched,last_scraped,source,name,description,neighborhood_overview,picture_url,...,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,region_id,region_name,region_parent_id,region_parent_name,region_parent_parent_id,region_parent_parent_name,reviews_per_month
0,1065244682287350993,https://www.airbnb.com/rooms/1065244682287350993,20260213082401,2026-02-13,2026-02-16,country scrape,Totara Ridge,Soak up the panoramic views from this peaceful...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,...,1,0,0,2499,Area Outside Ward,24,Rotorua District,NaN,NaN,5.65
1,43834420,https://www.airbnb.com/rooms/43834420,20260213082401,2026-02-13,2026-02-16,country scrape,Two Bedroom Access Apartment @ Riverlodge Motel,"Very spacious, wheelchair accessible two bedro...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,...,11,0,0,5299,Area Outside Ward,52,Nelson City,NaN,NaN,0.26
2,650824893416631133,https://www.airbnb.com/rooms/650824893416631133,20260213082401,2026-02-13,2026-02-16,country scrape,HOT TUB 4 bdr lake/town 5 min drive,This stylish home is simply stunning and light...,NaN,https://a0.muscache.com/pictures/befdbd05-ed1c...,...,15,0,0,7002,Wanaka Ward,70,Queenstown-Lakes District,NaN,NaN,6.94

In [16]:
df_apr.shape

(48951, 94)

In [17]:
df_apr.columns.tolist()

['id',
 'listing_url',
 'scrape_id',
 'last_searched',
 'last_scraped',
 'source',
 'name',
 'description',
 'neighborhood_overview',
 'picture_url',
 'host_id',
 'host_url',
 'host_name',
 'host_since',
 'hosts_time_as_user_years',
 'hosts_time_as_user_months',
 'hosts_time_as_host_years',
 'hosts_time_as_host_months',
 'host_location',
 'host_about',
 'host_response_time',
 'host_response_rate',
 'host_acceptance_rate',
 'host_is_superhost',
 'host_thumbnail_url',
 'host_picture_url',
 'host_neighbourhood',
 'host_listings_count',
 'host_total_listings_count',
 'host_verifications',
 'host_has_profile_pic',
 'host_identity_verified',
 'neighbourhood',
 'latitude',
 'longitude',
 'property_type',
 'room_type',
 'accommodates',
 'bathrooms',
 'bathrooms_text',
 'bedrooms',
 'beds',
 'amenities',
 'price',
 'price_quote_checkin_date',
 'price_quote_checkout_date',
 'price_quote_total_price',
 'price_quote_price_per_night',
 'price_quote_raw',
 'minimum_nights',
 'maximum_nights',
 'minimum_minimum_nights',
 'maximum_minimum_nights',
 'minimum_maximum_nights',
 'maximum_maximum_nights',
 'minimum_nights_avg_ntm',
 'maximum_nights_avg_ntm',
 'calendar_updated',
 'has_availability',
 'availability_30',
 'availability_60',
 'availability_90',
 'availability_365',
 'calendar_last_scraped',
 'number_of_reviews',
 'number_of_reviews_ltm',
 'number_of_reviews_l30d',
 'availability_eoy',
 'number_of_reviews_ly',
 'estimated_occupancy_l365d',
 'estimated_revenue_l365d',
 'first_review',
 'last_review',
 'review_scores_rating',
 'review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'requires_license',
 'license',
 'instant_bookable',
 'calculated_host_listings_count',
 'calculated_host_listings_count_entire_homes',
 'calculated_host_listings_count_private_rooms',
 'calculated_host_listings_count_shared_rooms',
 'region_id',
 'region_name',
 'region_parent_id',
 'region_parent_name',
 'region_parent_parent_id',
 'region_parent_parent_name',
 'reviews_per_month']

In [29]:
print(df_apr.dtypes.to_string())

id                                                int64
listing_url                                         str
scrape_id                                         int64
last_searched                                       str
last_scraped                                        str
source                                              str
name                                                str
description                                         str
neighborhood_overview                           float64
picture_url                                         str
host_id                                           int64
host_url                                            str
host_name                                           str
host_since                                      float64
hosts_time_as_user_years                        float64
hosts_time_as_user_months                       float64
hosts_time_as_host_years                        float64
hosts_time_as_host_months                       float64
host_location                                       str
host_about                                          str
host_response_time                              float64
host_response_rate                              float64
host_acceptance_rate                            float64
host_is_superhost                                   str
host_thumbnail_url                              float64
host_picture_url                                    str
host_neighbourhood                              float64
host_listings_count                             float64
host_total_listings_count                       float64
host_verifications                              float64
host_has_profile_pic                                str
host_identity_verified                              str
neighbourhood                                   float64
latitude                                        float64
longitude                                       float64
property_type                                       str
room_type                                           str
accommodates                                      int64
bathrooms                                       float64
bathrooms_text                                      str
bedrooms                                        float64
beds                                            float64
amenities                                           str
price                                               str
price_quote_checkin_date                            str
price_quote_checkout_date                           str
price_quote_total_price                         float64
price_quote_price_per_night                     float64
price_quote_raw                                     str
minimum_nights                                  float64
maximum_nights                                  float64
minimum_minimum_nights                          float64
maximum_minimum_nights                          float64
minimum_maximum_nights                          float64
maximum_maximum_nights                          float64
minimum_nights_avg_ntm                          float64
maximum_nights_avg_ntm                          float64
calendar_updated                                float64
has_availability                                    str
availability_30                                   int64
availability_60                                   int64
availability_90                                   int64
availability_365                                  int64
calendar_last_scraped                               str
number_of_reviews                                 int64
number_of_reviews_ltm                             int64
number_of_reviews_l30d                            int64
availability_eoy                                  int64
number_of_reviews_ly                              int64
estimated_occupancy_l365d                         int64
estimated_revenue_l365d                         float64
first_review                                        str
last_review                                         str
review_scores_rating                            float64
review_scores_accuracy                          float64
review_scores_cleanliness                       float64
review_scores_checkin                           float64
review_scores_communication                     float64
review_scores_location                          float64
review_scores_value                             float64
requires_license                                float64
license                                         float64
instant_bookable                                float64
calculated_host_listings_count                    int64
calculated_host_listings_count_entire_homes       int64
calculated_host_listings_count_private_rooms      int64
calculated_host_listings_count_shared_rooms       int64
region_id                                         int64
region_name                                         str
region_parent_id                                  int64
region_parent_name                                  str
region_parent_parent_id                         float64
region_parent_parent_name                       float64
reviews_per_month                               float64

In [19]:
df_apr.head(3)

,id,listing_url,scrape_id,last_searched,last_scraped,source,name,description,neighborhood_overview,picture_url,...,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,region_id,region_name,region_parent_id,region_parent_name,region_parent_parent_id,region_parent_parent_name,reviews_per_month
0,36194,https://www.airbnb.com/rooms/36194,20260416055825,2026-04-16,2026-04-22,country scrape,The Wharf Hub - a voyage,While many like to stay in our heritage accomm...,NaN,https://a0.muscache.com/pictures/c82b0a8b-39dd...,...,0,1,0,2702,Waioeka-Waiotahi Ward,27,Ōpōtiki District,NaN,NaN,0.07
1,46071,https://www.airbnb.com/rooms/46071,20260416055825,2026-04-16,2026-04-22,country scrape,Kamahi,"Relax, look out at the lake and listen to the ...",NaN,https://a0.muscache.com/pictures/0f3f1213-f297...,...,2,0,0,2103,Turangi-Tongariro Ward,21,Taupo District,NaN,NaN,0.36
2,51362,https://www.airbnb.com/rooms/51362,20260416055825,2026-04-16,2026-04-22,country scrape,PORTAGE HEIGHTS MARLBOROUGH SOUNDS,"Portage Heights lodge,Above Portage Resort, Hi...",NaN,https://a0.muscache.com/pictures/f6262847-b740...,...,0,1,0,5301,Marlborough Sounds Ward,53,Marlborough District,NaN,NaN,0.52

In [20]:
print(df_sum_feb['price'].dtypes)
print(df_sum_apr['price'].dtypes)
print(df_feb['price'].dtypes)
print(df_apr['price'].dtypes)

float64
float64
float64
str

In [21]:
print(df_sum_feb['price'].isnull().sum())
print(df_sum_apr['price'].isnull().sum())
print(df_feb['price'].isnull().sum())
print(df_apr['price'].isnull().sum())

48692
3844
48692
3844

In [22]:
print(df_sum_feb['price'].head(10))
print(df_sum_apr['price'].head(10))
print(df_feb['price'].head(10))
print(df_apr['price'].head(10))

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
Name: price, dtype: float64
0    150.0
1    360.0
2    343.0
3    373.0
4    137.0
5    137.0
6    101.0
7    286.0
8    206.0
9    252.0
Name: price, dtype: float64
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
Name: price, dtype: float64
0    $150.00
1    $359.50
2    $342.50
3    $373.00
4    $137.00
5    $137.00
6    $101.00
7    $286.00
8    $205.50
9    $252.00
Name: price, dtype: str

In [30]:
set(df_feb.columns) == set(df_apr.columns)

False

In [31]:
set(df_feb.columns) - set(df_apr.columns)

set()

In [31]:
set(df_apr.columns) - set(df_feb.columns)

{'hosts_time_as_host_months',
 'hosts_time_as_host_years',
 'hosts_time_as_user_months',
 'hosts_time_as_user_years',
 'price_quote_checkin_date',
 'price_quote_checkout_date',
 'price_quote_price_per_night',
 'price_quote_raw',
 'price_quote_total_price'}

In [32]:
print(df_feb.isnull().sum().to_string())

id                                                  0
listing_url                                         0
scrape_id                                           0
last_searched                                    1900
last_scraped                                        0
source                                              0
name                                                0
description                                       411
neighborhood_overview                           48692
picture_url                                         0
host_id                                             0
host_url                                            0
host_name                                           4
host_since                                      48692
host_location                                   10687
host_about                                      24987
host_response_time                              48692
host_response_rate                              48692
host_acceptance_rate                            48692
host_is_superhost                                   4
host_thumbnail_url                              48692
host_picture_url                                    4
host_neighbourhood                              48692
host_listings_count                                 4
host_total_listings_count                       48692
host_verifications                              48692
host_has_profile_pic                                4
host_identity_verified                              4
neighbourhood                                   48692
latitude                                            0
longitude                                           0
property_type                                       0
room_type                                           0
accommodates                                        0
bathrooms                                        1941
bathrooms_text                                     52
bedrooms                                          275
beds                                             1920
amenities                                           0
price                                           48692
minimum_nights                                    181
maximum_nights                                    181
minimum_minimum_nights                            181
maximum_minimum_nights                            181
minimum_maximum_nights                            181
maximum_maximum_nights                            181
minimum_nights_avg_ntm                              0
maximum_nights_avg_ntm                              0
calendar_updated                                48692
has_availability                                  297
availability_30                                     0
availability_60                                     0
availability_90                                     0
availability_365                                    0
calendar_last_scraped                               0
number_of_reviews                                   0
number_of_reviews_ltm                               0
number_of_reviews_l30d                              0
availability_eoy                                    0
number_of_reviews_ly                                0
estimated_occupancy_l365d                           0
estimated_revenue_l365d                         48692
first_review                                     4249
last_review                                      4249
review_scores_rating                             4249
review_scores_accuracy                           4250
review_scores_cleanliness                        4249
review_scores_checkin                            4250
review_scores_communication                      4250
review_scores_location                           4250
review_scores_value                              4250
requires_license                                48692
license                                         48692
instant_bookable                                48692
calculated_host_listings_count                      0
calculated_host_listings_count_entire_homes         0
calculated_host_listings_count_private_rooms        0
calculated_host_listings_count_shared_rooms         0
region_id                                           0
region_name                                         0
region_parent_id                                    0
region_parent_name                                  0
region_parent_parent_id                         48692
region_parent_parent_name                       48692
reviews_per_month                                4249

In [34]:
print(df_apr.isnull().sum().to_string())

id                                                  0
listing_url                                         0
scrape_id                                           0
last_searched                                    4863
last_scraped                                        0
source                                              0
name                                                0
description                                       413
neighborhood_overview                           48951
picture_url                                         0
host_id                                             0
host_url                                            0
host_name                                           3
host_since                                      48951
hosts_time_as_user_years                            3
hosts_time_as_user_months                           3
hosts_time_as_host_years                            3
hosts_time_as_host_months                           3
host_location                                   10830
host_about                                      24959
host_response_time                              48951
host_response_rate                              48951
host_acceptance_rate                            48951
host_is_superhost                                   3
host_thumbnail_url                              48951
host_picture_url                                    3
host_neighbourhood                              48951
host_listings_count                                 3
host_total_listings_count                       48951
host_verifications                              48951
host_has_profile_pic                                3
host_identity_verified                              3
neighbourhood                                   48951
latitude                                            0
longitude                                           0
property_type                                       0
room_type                                           0
accommodates                                        0
bathrooms                                        4891
bathrooms_text                                     43
bedrooms                                          761
beds                                             4879
amenities                                           0
price                                            3844
price_quote_checkin_date                         2342
price_quote_checkout_date                        2342
price_quote_total_price                          3854
price_quote_price_per_night                      3854
price_quote_raw                                  2342
minimum_nights                                      7
maximum_nights                                      7
minimum_minimum_nights                              7
maximum_minimum_nights                              7
minimum_maximum_nights                              7
maximum_maximum_nights                              7
minimum_nights_avg_ntm                              0
maximum_nights_avg_ntm                              0
calendar_updated                                48951
has_availability                                  285
availability_30                                     0
availability_60                                     0
availability_90                                     0
availability_365                                    0
calendar_last_scraped                               0
number_of_reviews                                   0
number_of_reviews_ltm                               0
number_of_reviews_l30d                              0
availability_eoy                                    0
number_of_reviews_ly                                0
estimated_occupancy_l365d                           0
estimated_revenue_l365d                          3844
first_review                                     4136
last_review                                      4136
review_scores_rating                             4136
review_scores_accuracy                           4137
review_scores_cleanliness                        4136
review_scores_checkin                            4137
review_scores_communication                      4137
review_scores_location                           4137
review_scores_value                              4137
requires_license                                48951
license                                         48951
instant_bookable                                48951
calculated_host_listings_count                      0
calculated_host_listings_count_entire_homes         0
calculated_host_listings_count_private_rooms        0
calculated_host_listings_count_shared_rooms         0
region_id                                           0
region_name                                         0
region_parent_id                                    0
region_parent_name                                  0
region_parent_parent_id                         48951
region_parent_parent_name                       48951
reviews_per_month                                4136