In [16]:
import pandas as pd
import geopandas as gpd
pd.set_option('display.max_rows', None)

In [17]:
listings = pd.read_csv("../data/raw/listings.csv.gz")
neighbourhoods = pd.read_csv("../data/raw/neighbourhoods.csv")
neighbourhoods_geo = gpd.read_file("../data/raw/neighbourhoods.geojson")

In [18]:
listings.shape

(46321, 85)

In [19]:
listings.columns.tolist()

['id',
 'listing_url',
 'scrape_id',
 'last_searched',
 'last_scraped',
 'source',
 'name',
 'description',
 'neighborhood_overview',
 'picture_url',
 'host_id',
 'host_url',
 'host_name',
 'host_since',
 'host_location',
 'host_about',
 'host_response_time',
 'host_response_rate',
 'host_acceptance_rate',
 'host_is_superhost',
 'host_thumbnail_url',
 'host_picture_url',
 'host_neighbourhood',
 'host_listings_count',
 'host_total_listings_count',
 'host_verifications',
 'host_has_profile_pic',
 'host_identity_verified',
 'neighbourhood',
 'latitude',
 'longitude',
 'property_type',
 'room_type',
 'accommodates',
 'bathrooms',
 'bathrooms_text',
 'bedrooms',
 'beds',
 'amenities',
 'price',
 'minimum_nights',
 'maximum_nights',
 'minimum_minimum_nights',
 'maximum_minimum_nights',
 'minimum_maximum_nights',
 'maximum_maximum_nights',
 'minimum_nights_avg_ntm',
 'maximum_nights_avg_ntm',
 'calendar_updated',
 'has_availability',
 'availability_30',
 'availability_60',
 'availability_90',
 'availability_365',
 'calendar_last_scraped',
 'number_of_reviews',
 'number_of_reviews_ltm',
 'number_of_reviews_l30d',
 'availability_eoy',
 'number_of_reviews_ly',
 'estimated_occupancy_l365d',
 'estimated_revenue_l365d',
 'first_review',
 'last_review',
 'review_scores_rating',
 'review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'requires_license',
 'license',
 'instant_bookable',
 'calculated_host_listings_count',
 'calculated_host_listings_count_entire_homes',
 'calculated_host_listings_count_private_rooms',
 'calculated_host_listings_count_shared_rooms',
 'region_id',
 'region_name',
 'region_parent_id',
 'region_parent_name',
 'region_parent_parent_id',
 'region_parent_parent_name',
 'reviews_per_month']

In [21]:
print(listings.isnull().sum().sort_values(ascending=False))

license                                         46321
region_parent_parent_name                       46321
region_parent_parent_id                         46321
requires_license                                46321
calendar_updated                                46321
host_neighbourhood                              46246
host_about                                      24494
neighborhood_overview                           23782
neighbourhood                                   23782
host_response_rate                              10018
host_response_time                              10018
host_location                                    9818
host_acceptance_rate                             6492
review_scores_communication                      5103
review_scores_accuracy                           5103
review_scores_checkin                            5103
review_scores_value                              5103
review_scores_location                           5103
reviews_per_month                                5102
review_scores_rating                             5102
first_review                                     5102
review_scores_cleanliness                        5102
last_review                                      5102
price                                            1555
estimated_revenue_l365d                          1555
bathrooms                                        1539
beds                                             1538
last_searched                                    1514
host_is_superhost                                1074
description                                       453
has_availability                                  364
bedrooms                                          270
bathrooms_text                                     36
host_identity_verified                             15
host_thumbnail_url                                 15
host_name                                          15
host_since                                         15
host_listings_count                                15
host_has_profile_pic                               15
host_verifications                                 15
host_picture_url                                   15
host_total_listings_count                          15
maximum_maximum_nights                             10
maximum_minimum_nights                             10
minimum_maximum_nights                             10
minimum_minimum_nights                             10
id                                                  0
host_id                                             0
name                                                0
host_url                                            0
listing_url                                         0
scrape_id                                           0
last_scraped                                        0
source                                              0
picture_url                                         0
availability_90                                     0
maximum_nights_avg_ntm                              0
minimum_nights_avg_ntm                              0
availability_60                                     0
availability_30                                     0
maximum_nights                                      0
room_type                                           0
property_type                                       0
longitude                                           0
latitude                                            0
accommodates                                        0
amenities                                           0
minimum_nights                                      0
estimated_occupancy_l365d                           0
availability_365                                    0
calendar_last_scraped                               0
number_of_reviews                                   0
number_of_reviews_ltm                               0
number_of_reviews_l30d                              0
availability_eoy                                    0
number_of_reviews_ly                                0
instant_bookable                                    0
calculated_host_listings_count_private_rooms        0
calculated_host_listings_count_entire_homes         0
calculated_host_listings_count                      0
calculated_host_listings_count_shared_rooms         0
region_parent_id                                    0
region_name                                         0
region_id                                           0
region_parent_name                                  0
dtype: int64

In [24]:
(listings.isnull().mean() * 100).sort_values(ascending=False)

license                                         100.000000
region_parent_parent_name                       100.000000
region_parent_parent_id                         100.000000
requires_license                                100.000000
calendar_updated                                100.000000
host_neighbourhood                               99.838086
host_about                                       52.878824
neighborhood_overview                            51.341724
neighbourhood                                    51.341724
host_response_rate                               21.627340
host_response_time                               21.627340
host_location                                    21.195570
host_acceptance_rate                             14.015241
review_scores_communication                      11.016602
review_scores_accuracy                           11.016602
review_scores_checkin                            11.016602
review_scores_value                              11.016602
review_scores_location                           11.016602
reviews_per_month                                11.014443
review_scores_rating                             11.014443
first_review                                     11.014443
review_scores_cleanliness                        11.014443
last_review                                      11.014443
price                                             3.357009
estimated_revenue_l365d                           3.357009
bathrooms                                         3.322467
beds                                              3.320308
last_searched                                     3.268496
host_is_superhost                                 2.318603
description                                       0.977958
has_availability                                  0.785821
bedrooms                                          0.582889
bathrooms_text                                    0.077719
host_identity_verified                            0.032383
host_thumbnail_url                                0.032383
host_name                                         0.032383
host_since                                        0.032383
host_listings_count                               0.032383
host_has_profile_pic                              0.032383
host_verifications                                0.032383
host_picture_url                                  0.032383
host_total_listings_count                         0.032383
maximum_maximum_nights                            0.021588
maximum_minimum_nights                            0.021588
minimum_maximum_nights                            0.021588
minimum_minimum_nights                            0.021588
id                                                0.000000
host_id                                           0.000000
name                                              0.000000
host_url                                          0.000000
listing_url                                       0.000000
scrape_id                                         0.000000
last_scraped                                      0.000000
source                                            0.000000
picture_url                                       0.000000
availability_90                                   0.000000
maximum_nights_avg_ntm                            0.000000
minimum_nights_avg_ntm                            0.000000
availability_60                                   0.000000
availability_30                                   0.000000
maximum_nights                                    0.000000
room_type                                         0.000000
property_type                                     0.000000
longitude                                         0.000000
latitude                                          0.000000
accommodates                                      0.000000
amenities                                         0.000000
minimum_nights                                    0.000000
estimated_occupancy_l365d                         0.000000
availability_365                                  0.000000
calendar_last_scraped                             0.000000
number_of_reviews                                 0.000000
number_of_reviews_ltm                             0.000000
number_of_reviews_l30d                            0.000000
availability_eoy                                  0.000000
number_of_reviews_ly                              0.000000
instant_bookable                                  0.000000
calculated_host_listings_count_private_rooms      0.000000
calculated_host_listings_count_entire_homes       0.000000
calculated_host_listings_count                    0.000000
calculated_host_listings_count_shared_rooms       0.000000
region_parent_id                                  0.000000
region_name                                       0.000000
region_id                                         0.000000
region_parent_name                                0.000000
dtype: float64

In [28]:
listings.head(5)

,id,listing_url,scrape_id,last_searched,last_scraped,source,name,description,neighborhood_overview,picture_url,...,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,region_id,region_name,region_parent_id,region_parent_name,region_parent_parent_id,region_parent_parent_name,reviews_per_month
0,1419869766929384483,https://www.airbnb.com/rooms/1419869766929384483,20250704005853,NaN,2025-07-04,previous scrape,Cozy Queen Room,Take it easy at this unique and tranquil getaway.,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,...,0,2,0,7001,Queenstown-Wakatipu Ward,70,Queenstown-Lakes District,NaN,NaN,NaN
1,1417531189274342484,https://www.airbnb.com/rooms/1417531189274342484,20250704005853,2025-07-04,2025-07-05,country scrape,Cozy Apartment for Rent,Keep it simple at this peaceful and centrally-...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,...,1,0,0,7607,Albert-Eden-Puketāpapa Ward,76,Auckland,NaN,NaN,NaN
2,1352305286886592525,https://www.airbnb.com/rooms/1352305286886592525,20250704005853,2025-07-04,2025-07-04,country scrape,Fabulous Home for Winter,Have fun with the whole family at this stylish...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,...,1,0,0,7001,Queenstown-Wakatipu Ward,70,Queenstown-Lakes District,NaN,NaN,NaN
3,29438313,https://www.airbnb.com/rooms/29438313,20250704005853,2025-07-04,2025-07-04,country scrape,5 bedroom beauty in Lake Hayes Estate,NaN,NaN,https://a0.muscache.com/pictures/cdfc5ac3-3af2...,...,1,1,0,7001,Queenstown-Wakatipu Ward,70,Queenstown-Lakes District,NaN,NaN,0.04
4,1447387314700756673,https://www.airbnb.com/rooms/1447387314700756673,20250704005853,2025-07-04,2025-07-04,country scrape,Stylish Renovated Villa,Relax with the whole family at this peaceful p...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,...,1,0,0,6005,Innes Ward,60,Christchurch City,NaN,NaN,NaN

In [29]:
listings['price'].head(5)

0        NaN
1    $120.00
2    $315.00
3    $603.00
4    $159.00
Name: price, dtype: str

In [36]:
listings['host_neighbourhood'].nunique()

43

In [43]:
listings['neighbourhood'].nunique()

1996

In [44]:
listings['neighborhood_overview'].nunique()

18835

In [45]:
neighbourhoods.shape

(239, 2)

In [46]:
neighbourhoods_geo.head()

,neighbourhood,neighbourhood_group,geometry
0,Waipaoa Ward,Gisborne District,"MULTIPOLYGON (((177.29832 -38.40158, 177.34641..."
1,Tawhiti-Uawa Ward,Gisborne District,"MULTIPOLYGON (((178.34318 -38.37897, 178.34336..."
2,Taruheru-Patutahi Ward,Gisborne District,"MULTIPOLYGON (((177.88188 -38.62445, 177.8821 ..."
3,Gisborne Ward,Gisborne District,"MULTIPOLYGON (((178.04868 -38.70512, 178.04876..."
4,Wairoa General Ward,Wairoa District,"MULTIPOLYGON (((177.87094 -39.27634, 177.87097..."

In [47]:
listings.dtypes

id                                                int64
listing_url                                         str
scrape_id                                         int64
last_searched                                       str
last_scraped                                        str
source                                              str
name                                                str
description                                         str
neighborhood_overview                               str
picture_url                                         str
host_id                                           int64
host_url                                            str
host_name                                           str
host_since                                          str
host_location                                       str
host_about                                          str
host_response_time                                  str
host_response_rate                                  str
host_acceptance_rate                                str
host_is_superhost                                   str
host_thumbnail_url                                  str
host_picture_url                                    str
host_neighbourhood                                  str
host_listings_count                             float64
host_total_listings_count                       float64
host_verifications                                  str
host_has_profile_pic                                str
host_identity_verified                              str
neighbourhood                                       str
latitude                                        float64
longitude                                       float64
property_type                                       str
room_type                                           str
accommodates                                      int64
bathrooms                                       float64
bathrooms_text                                      str
bedrooms                                        float64
beds                                            float64
amenities                                           str
price                                               str
minimum_nights                                    int64
maximum_nights                                    int64
minimum_minimum_nights                          float64
maximum_minimum_nights                          float64
minimum_maximum_nights                          float64
maximum_maximum_nights                          float64
minimum_nights_avg_ntm                          float64
maximum_nights_avg_ntm                          float64
calendar_updated                                float64
has_availability                                    str
availability_30                                   int64
availability_60                                   int64
availability_90                                   int64
availability_365                                  int64
calendar_last_scraped                               str
number_of_reviews                                 int64
number_of_reviews_ltm                             int64
number_of_reviews_l30d                            int64
availability_eoy                                  int64
number_of_reviews_ly                              int64
estimated_occupancy_l365d                         int64
estimated_revenue_l365d                         float64
first_review                                        str
last_review                                         str
review_scores_rating                            float64
review_scores_accuracy                          float64
review_scores_cleanliness                       float64
review_scores_checkin                           float64
review_scores_communication                     float64
review_scores_location                          float64
review_scores_value                             float64
requires_license                                float64
license                                         float64
instant_bookable                                    str
calculated_host_listings_count                    int64
calculated_host_listings_count_entire_homes       int64
calculated_host_listings_count_private_rooms      int64
calculated_host_listings_count_shared_rooms       int64
region_id                                         int64
region_name                                         str
region_parent_id                                  int64
region_parent_name                                  str
region_parent_parent_id                         float64
region_parent_parent_name                       float64
reviews_per_month                               float64
dtype: object